### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by henryadamsjr** [AlexanderSharykin/CardIdleRemastered#40]
Not sure if this is still being worked on, but I've tried to login on two different computers, and I get the same issue.  This is the error log:

2/4/2019 6:32:44 PM   Microsoft Windows NT 6.1.7601 Service Pack 1 64bit
2/4/2019 6:32:44 PM   C:\Users\<USER>\AppData\Local\CardIdleRemastered\Settings.txt
Settings storage file not found.
2/4/2019 6:32:45 PM   Login required
2/4/2019 6:32:45 PM   DispatcherUnhandledException
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CardIdleRemastered.SteamParser.<DownloadString>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CardIdleRemastered.SteamParser.<GetLatestCardIdlerRelease>d__2b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CardIdleRemastered.AccountModel.<CheckLatestRelease>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2/4/2019 6:32:50 PM   Navigated to https://steamcommunity.com/login/home/?goto=my/profile
2/4/2019 6:33:13 PM   Navigated to https://steamcommunity.com/id/<USER>
2/4/2019 6:33:17 PM   Login required

**Comment by AlexanderSharykin** [comment]
Hello
I do provide support for CIR.
Is it possible that you are using some old version (there were some issues with check for updates, which gave ssl/tls error). If so, try (download-unzip-run) the latest version from releases (https://github.com/AlexanderSharykin/CardIdleRemastered/releases)

You can check your current version in CardIdleRemastered.exe properties:
![cir version](https://user-images.githubusercontent.com/6756469/52578924-4018f580-2e36-11e9-88d4-43f033504a2b.png)
